### PR TITLE
Web app

### PR DESCRIPTION
**Pull request by AmbitiousFlowDev**

### CODE REVIEW

**Review by AmbitiousFlowDev — COMMENTED** [review]
**OpenCV on a small project was a terible idea !**

**Comment by Mitra-88** [comment]
its fast in some cases but the old image generation code was bad :D
its way better now check it out

**Comment by Mitra-88** [comment]
i need you to explain a lot of stuff to me on discord 
im about to refactor the whole thing because I dont understand a thing

**Comment by AmbitiousFlowDev** [comment]
Of course

**Pull request closed without merging**
